### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hakxcore** [TheHamkerCat/Music_Downloader_CLI#3]
┌──(user㉿hakxcore)-[~/Music/Music_Downloader_CLI]
└─$ python3 main.py    
Traceback (most recent call last):
  File "/home/user1/Music/Music_Downloader_CLI/main.py", line 10, in <module>
    from config import ARQ_API_KEY
ImportError: cannot import name 'ARQ_API_KEY' from 'config' (/home/user1/.local/lib/python3.9/site-packages/config/__init__.py)

Also may 'config' module isn't in requirements file.

**Comment by TheHamkerCat** [comment]
create a file named config.py then write `ARQ_API_KEY = "Your api key"` in it, and run again
